<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Services\GeminiService;
use Illuminate\Support\Facades\Auth;

class ArticleController extends Controller
{
    protected $geminiService;

    public function __construct(GeminiService $geminiService)
    {
        $this->geminiService = $geminiService;
    }

    // News Feed Display (with Filtering and Search)
    public function index(Request $request)
    {
        $query = Article::with('category')->orderBy('published_at', 'desc');

        // Filter by category (using slug or ID)
        if ($request->has('category')) {
            $categoryIdentifier = $request->input('category');
            $category = Category::where('slug', $categoryIdentifier)->orWhere('id', $categoryIdentifier)->first();
            if ($category) {
                $query->where('category_id', $category->id);
            }
        }

        // Filter by source
        if ($request->has('source')) {
            $query->where('source', 'like', '%' . $request->input('source') . '%');
        }

        // Search by keyword (in title or content)
        if ($request->has('keyword')) {
            $keyword = $request->input('keyword');
            $query->where(function ($q) use ($keyword) {
                $q->where('title', 'like', '%' . $keyword . '%')
                  ->orWhere('content', 'like', '%' . $keyword . '%');
            });
        }

        $articles = $query->paginate(10); // Paginate results
        return response()->json($articles);
    }

    // Display a single article
    public function show(Article $article)
    {
        return response()->json($article->load('category'));
    }

    // Article Summarization
    public function summarize(Article $article)
    {
        $summary = $this->geminiService->summarizeText($article->content);
        return response()->json([
            'article_id' => $article->id,
            'title' => $article->title,
            'original_content_length' => strlen($article->content),
            'summary' => $summary,
            'ai_disclaimer' => 'This summary was generated by AI. Use responsibly and verify critical information.'
        ]);
    }

    // Save Article for Later
    public function saveForLater(Request $request, Article $article)
    {
        $user = Auth::user();
        if ($user->savedArticles()->where('article_id', $article->id)->exists()) {
            return response()->json(['message' => 'Article already saved.'], 409); // Conflict
        }
        $user->savedArticles()->attach($article->id);
        return response()->json(['message' => 'Article saved for later.']);
    }

    // Unsave Article
    public function unsaveArticle(Request $request, Article $article)
    {
        $user = Auth::user();
        if ($user->savedArticles()->detach($article->id)) {
            return response()->json(['message' => 'Article unsaved.']);
        }
        return response()->json(['message' => 'Article was not in your saved list.'], 404);
    }

    // List Saved Articles for current user
    public function listSaved(Request $request)
    {
        $user = Auth::user();
        $savedArticles = $user->savedArticles()->with('category')->orderBy('pivot_created_at', 'desc')->paginate(10);
        return response()->json($savedArticles);
    }
}