<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Services\GeminiService;
use Illuminate\Http\Request;
use Carbon\Carbon;

class DigestController extends Controller
{
    protected $geminiService;

    public function __construct(GeminiService $geminiService)
    {
        $this->geminiService = $geminiService;
    }

    public function generateDailyDigest(Request $request)
    {
        $topArticles = Article::where('published_at', '>=', Carbon::now()->subDay())
                              ->orderBy('published_at', 'desc')
                              ->take(5)->get();

        if ($topArticles->isEmpty()) {
            return back()->with('digest_error', 'Not enough recent articles to generate a digest.');
        }

        $digestText = $this->geminiService->generateDailyDigest($topArticles->all());

        if (str_starts_with($digestText, "Error")) { // Check if GeminiService returned an error string
             return back()->with('digest_error', $digestText);
        }

        $digestData = [
            'digest_date' => Carbon::now()->toDateString(),
            'daily_digest' => $digestText,
            'source_articles_count' => $topArticles->count(),
            'ai_disclaimer' => 'This digest was generated by AI. Use responsibly.'
        ];

        return back()->with('daily_digest', $digestData);
    }
}