<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Services\GeminiService;
use Illuminate\Http\Request;
use Carbon\Carbon;

class DigestController extends Controller
{
    protected $geminiService;

    public function __construct(GeminiService $geminiService)
    {
        $this->geminiService = $geminiService;
    }

    public function generateDailyDigest(Request $request)
    {
        // Get top N articles (e.g., 5 most recent from the last 24 hours)
        // Adjust logic as needed for what "top stories" means
        $topArticles = Article::where('published_at', '>=', Carbon::now()->subDay())
                              ->orderBy('published_at', 'desc')
                              ->take(5) // Take top 5
                              ->get();

        if ($topArticles->isEmpty()) {
            return response()->json(['message' => 'Not enough recent articles to generate a digest.']);
        }

        $digest = $this->geminiService->generateDailyDigest($topArticles->all());

        return response()->json([
            'digest_date' => Carbon::now()->toDateString(),
            'daily_digest' => $digest,
            'source_articles_count' => $topArticles->count(),
            'ai_disclaimer' => 'This digest was generated by AI. Use responsibly and verify critical information.'
        ]);
    }
}