@extends('layouts.app')

@section('title', 'Article Summary - ' . Str::limit($article->title, 30))

@section('content')
<div class="bg-white rounded-lg shadow-sm p-6 md:p-8">
    <div class="mb-6 pb-4 border-b border-gray-200">
        <a href="{{ route('home') }}" class="text-blue-600 hover:underline text-sm mb-2 inline-block">
            ← Back to Home
        </a>
        <h1 class="text-2xl md:text-3xl font-bold text-gray-900 mb-2">
            {{ $article->title }}
        </h1>
        <p class="text-sm text-gray-500">
            Source: {{ $article->source }} | Category: {{ $article->category->name ?? 'N/A' }} | Published: {{ $article->published_at->format('M d, Y') }}
        </p>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div class="lg:col-span-2 prose max-w-none">
            <h2 class="text-xl font-semibold text-gray-800 mb-3">Full Article Content</h2>
            {!! nl2br(e($article->content)) !!}
        </div>

        <div class="lg:col-span-1">
            <div class="bg-blue-50 p-4 rounded-lg shadow">
                <div class="flex items-center gap-2 mb-3">
                    <i data-lucide="bot" class="text-blue-500 w-5 h-5"></i>
                    <h2 class="text-xl font-semibold text-blue-700">AI Generated Summary</h2>
                </div>
                @if (is_string($summary) && str_starts_with($summary, "Error"))
                    <p class="text-red-600">{{ $summary }}</p>
                @elseif (!empty($summary))
                    <p class="text-gray-700 leading-relaxed whitespace-pre-wrap">{{ $summary }}</p>
                    <p class="text-xs text-gray-500 mt-3">
                        <em>This summary was generated by AI. Use responsibly and verify critical information.</em>
                    </p>
                @else
                    <p class="text-gray-600">Summary could not be generated or is unavailable.</p>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection